# -*- coding: utf-8 -*-
"""Feedback_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzLA-_dEuGdTW17yrnvqlHZeZ4W13Qk6
"""

!pip install supabase pandas python-dotenv pydantic

!mv supabase.env .env

import pandas as pd
from supabase import create_client, Client
import os
from dotenv import load_dotenv
from datetime import datetime

# Load environment variables
load_dotenv(".env")

# Supabase configuration
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

def format_phone_number(phone):
    """Format phone number to include +88 prefix"""
    if pd.isna(phone):
        return None

    # Convert to string and remove any non-digit characters
    phone_str = ''.join(filter(str.isdigit, str(phone)))

    # If empty after cleaning, return None
    if not phone_str:
        return None

    # If already starts with 88, just add the +
    if phone_str.startswith('88'):
        return f"+{phone_str}"

    # Otherwise, add +88
    return f"+88{phone_str}"

def convert_rating(value):
    """Convert rating strings to integers"""
    rating_map = {
        'poor': 1,
        'fair': 2,
        'good': 3,
        'great': 4
    }

    if pd.isna(value):
        return 1  # Default to 1 for missing values

    cleaned_value = str(value).lower().strip()
    return rating_map.get(cleaned_value, 1)

def format_date(date, time):
    """Format date and time properly"""
    try:
        if pd.isna(time):
            dt = pd.to_datetime(date)
        else:
            dt = pd.to_datetime(f"{date} {time}")
        return dt.isoformat()
    except:
        return datetime.now().isoformat()

def get_or_create_customer(row):
    """Get existing customer ID or create new customer"""
    try:
        raw_phone = str(row["Phone Number"]).strip() if not pd.isna(row["Phone Number"]) else None
        phone_number = format_phone_number(raw_phone) if raw_phone else None
        email = str(row["Email"]).strip() if not pd.isna(row["Email"]) else None

        # Try to find existing customer by phone or email
        existing_customer = None
        if phone_number:
            phone_response = supabase.table("customers").select("customer_id").eq("phone_number", phone_number).execute()
            if phone_response.data:
                existing_customer = phone_response.data[0]

        if not existing_customer and email:
            email_response = supabase.table("customers").select("customer_id").eq("email", email).execute()
            if email_response.data:
                existing_customer = email_response.data[0]

        if existing_customer:
            return existing_customer["customer_id"]

        # Create new customer if not found
        customer_data = {
            "name": str(row["Customer Name"]).strip() if not pd.isna(row["Customer Name"]) else "",
            "email": email,
            "phone_number": phone_number,  # This now includes the +88 prefix
            "address": str(row["Address"]).strip() if not pd.isna(row["Address"]) else ""
        }

        new_customer = supabase.table("customers").insert(customer_data).execute()
        return new_customer.data[0]["customer_id"]

    except Exception as e:
        print(f"Error in get_or_create_customer: {e}")
        return None

def insert_feedback(row):
    """Insert feedback data for a customer"""
    try:
        # Get or create customer
        customer_id = get_or_create_customer(row)
        if not customer_id:
            print("Could not get or create customer, skipping feedback")
            return False

        # Prepare feedback data
        feedback_data = {
            "customer_id": customer_id,
            "food_review": convert_rating(row.get("Food Review")),
            "service": convert_rating(row.get("Service")),
            "cleanliness": convert_rating(row.get("Cleanliness")),
            "atmosphere": convert_rating(row.get("Atmosphere")),
            "value": convert_rating(row.get("Value")),
            "overall_experience": convert_rating(row.get("Overall Experience")),
            # "feedback_text": str(row.get("How did you hear about us", "")).strip() if not pd.isna(row.get("How did you hear about us")) else "",
            "feedback_date": format_date(row['Date'], row.get('Time'))
        }

        # Insert feedback
        feedback_response = supabase.table("feedback").insert(feedback_data).execute()
        print(f"Successfully inserted feedback for customer {customer_id}")
        return True

    except Exception as e:
        print(f"Error inserting feedback: {e}")
        return False

def main():
    try:
        # Load the feedback data from Excel
        file_path = "/content/Feedback Forms Data (1).xlsx"
        feedback_df = pd.read_excel(file_path)

        total_rows = len(feedback_df)
        successful_inserts = 0
        failed_inserts = 0

        print(f"Processing {total_rows} rows...")

        # Process each row
        for index, row in feedback_df.iterrows():
            print(f"\nProcessing row {index + 1} of {total_rows}")
            if insert_feedback(row):
                successful_inserts += 1
            else:
                failed_inserts += 1

        print(f"\nImport completed!")
        print(f"Successfully inserted: {successful_inserts}")
        print(f"Failed to insert: {failed_inserts}")

    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    main()