# -*- coding: utf-8 -*-
"""ServQuick_data_import_to_Supabase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rC8gd5XrvPMO2Zo0dflgTjNIxQfO-jLp
"""

!pip install supabase pandas python-dotenv pydantic

!mv supabase.env .env

"""## ServQuick data"""

import os
import pandas as pd
import uuid
from supabase import create_client, Client
from dotenv import load_dotenv
from datetime import datetime

# Load environment variables
load_dotenv(".env")

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

if not SUPABASE_URL or not SUPABASE_KEY:
    raise ValueError("Supabase credentials are missing. Check your .env file.")

# Initialize Supabase client
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

# Function to standardize phone numbers
def standardize_phone_number(phone_number):
    # Remove spaces, dashes, and other non-numeric characters
    phone_number = "".join(filter(str.isdigit, phone_number))

    # Add the country code +880 if not already present
    if not phone_number.startswith("+880"):
        if phone_number.startswith("0"):
            phone_number = "880" + phone_number[1:]  # Remove leading zero
        elif phone_number.startswith("880"):
            phone_number = phone_number
        else:
            phone_number = "880" + phone_number

    return f"+{phone_number}"  # Add the '+' prefix

# Function to insert unique customers
def insert_customer(customer):
    # Standardize phone number
    customer["phone_number"] = standardize_phone_number(customer["phone_number"])

    # Check if the customer already exists
    existing_customer = supabase.table("customers").select("*").eq("phone_number", customer["phone_number"]).execute()
    if not existing_customer.data:
        customer_id = str(uuid.uuid4())  # Generate a unique ID for the customer
        customer["customer_id"] = customer_id

        # Ensure all values in the customer dictionary are valid JSON types
        for key, value in customer.items():
            if pd.isnull(value):  # Check for NaN values
                customer[key] = None  # Replace NaN with None
            elif isinstance(value, float) and (pd.isna(value) or value == float('inf') or value == float('-inf')):
                customer[key] = None  # Replace infinite or NaN floats with None

        supabase.table("customers").insert(customer).execute()
        return customer_id
    return existing_customer.data[0]["customer_id"]

# Function to insert unique orders
def insert_order(order):
    supabase.table("orders").insert(order).execute()

def process_excel(file_path):
    # Read the Excel file
    data = pd.read_excel(file_path)

    column_map = {
        "Customer name": "Customer name",
        "Customer mobile": "Customer mobile",
        "Customer email": "Customer email",
        "Customer address": "Customer address",
        "Sale date": "Sale date",
        "Receipt no": "Receipt no",  # Used for grouping and stored as ServQuick Receipt ID
        "Ordertype name": "Ordertype name",
        "Item name": "Item name",
        "Variant name": "Variant name",
        "Selling price": "Selling price",
        "Item quantity": "Item quantity",
        "Item amount": "Item amount",
    }

    # Ensure the necessary columns exist
    required_columns = column_map.keys()
    for col in required_columns:
        if col not in data.columns:
            raise ValueError(f"Missing required column: {col}")

    # Convert numeric columns to proper types
    data["Item quantity"] = pd.to_numeric(data["Item quantity"], errors="coerce")
    data["Item amount"] = pd.to_numeric(data["Item amount"], errors="coerce")

    # Group items by receipt number (used only for grouping here)
    grouped = data.groupby("Receipt no").apply(lambda group: {
        "order_items": group.apply(lambda row: {
            "item_name": row["Item name"],
            "quantity": row["Item quantity"],
            "amount": row["Item amount"],
        }, axis=1).tolist(),
        "order_items_text": "; ".join(
            f'{row["Item name"]} (x{row["Item quantity"]})' for _, row in group.iterrows()
        ),
    }).reset_index(name="grouped_data")

    # Extract grouped data into a DataFrame
    grouped_data = pd.json_normalize(grouped["grouped_data"])
    grouped = pd.concat([grouped, grouped_data], axis=1)

    # Merge grouped data back with the original dataset
    final_data = pd.merge(data.drop_duplicates("Receipt no"), grouped, on="Receipt no", how="left")

    # Define a mapping for valid order types
    order_type_map = {
        "Dine-In": "Dine-In",
        "Delivery": "Delivery",
        "Takeaway": "Take away",  # Map "Takeaway" to "Take away"
        "Take away": "Take away",  # Allow direct match
        "Eat in": "Dine-In",       # Handle alternate naming
    }

    # Process customers and orders
    for _, row in final_data.iterrows():
        # Extract customer details
        customer = {
            "name": row[column_map["Customer name"]],
            "phone_number": row[column_map["Customer mobile"]],
            "email": row[column_map["Customer email"]],
            "address": row[column_map["Customer address"]],
        }

        # Insert the customer and retrieve their ID
        customer_id = insert_customer(customer)

        # Skip if customer insertion fails
        if not customer_id:
            continue

        # Get and validate the order type
        order_type = row[column_map["Ordertype name"]]
        if order_type not in order_type_map:
            print(f"Skipping order with invalid order type: {order_type}")
            continue

        # Prepare order details
        order = {
            "order_id": str(uuid.uuid4()),  # Generate a unique ID for the order
            "customer_id": customer_id,
            "order_date": row[column_map["Sale date"]].isoformat()
            if isinstance(row[column_map["Sale date"]], pd.Timestamp)
            else str(row[column_map["Sale date"]]),
            "order_items": row["order_items"],
            "order_items_text": row["order_items_text"],
            "total_amount": sum(item["amount"] for item in row["order_items"]),
            "order_type": order_type_map[order_type],  # Map to a valid enum type
            "receipt_id": row[column_map["Receipt no"]],  # ServQuick receipt ID
        }

        # Insert the order
        try:
            insert_order(order)
        except Exception as e:
            print(f"Failed to insert order: {e}")

    print("Data successfully inserted into Supabase.")

# Example usage
if __name__ == "__main__":
    # Provide the path to your Excel file
    excel_file_path = "/content/Sales_deta_by_receipt_last_year.xls"  # Replace with your file path
    process_excel(excel_file_path)







